update=di 16 feb 2016 11:03:49 CET
version=1
last_client=kicad
[pcbnew]
version=1
LastNetListRead=
UseCmpFile=1
PadDrill=0.600000000000
PadDrillOvalY=0.600000000000
PadSizeH=1.500000000000
PadSizeV=1.500000000000
PcbTextSizeV=1.500000000000
PcbTextSizeH=1.500000000000
PcbTextThickness=0.300000000000
ModuleTextSizeV=1.000000000000
ModuleTextSizeH=1.000000000000
ModuleTextSizeThickness=0.150000000000
SolderMaskClearance=0.000000000000
SolderMaskMinWidth=0.000000000000
DrawSegmentWidth=0.200000000000
BoardOutlineThickness=0.100000000000
ModuleOutlineThickness=0.150000000000
[cvpcb]
version=1
NetIExt=net
[general]
version=1
[schematic_editor]
version=1
PageLayoutDescrFile=
PlotDirectoryName=
SubpartIdSeparator=0
SubpartFirstId=65
NetFmtName=
SpiceForceRefPrefix=0
SpiceUseNetNumbers=0
LabSize=60
[eeschema]
version=1
LibDir=../../../share/kicad/library/lib_michiel;../../../share/kicad/library/walter
[eeschema/libraries]
LibName1=MiG-21bis Brandstofpaneel_v01-rescue
LibName2=C:/Program Files/KiCad/share/kicad/library/~GNDPWR
LibName3=C:/Program Files/KiCad/share/kicad/library/+1.8V
LibName4=C:/Program Files/KiCad/share/kicad/library/+3.3V
LibName5=C:/Program Files/KiCad/share/kicad/library/+5V
LibName6=C:/Program Files/KiCad/share/kicad/library/+9V
LibName7=C:/Program Files/KiCad/share/kicad/library/25AA02EXXX-XOT
LibName8=C:/Program Files/KiCad/share/kicad/library/74LVC8T245
LibName9=C:/Program Files/KiCad/share/kicad/library/74xgxx
LibName10=C:/Program Files/KiCad/share/kicad/library/74xx
LibName11=C:/Program Files/KiCad/share/kicad/library/4021
LibName12=C:/Program Files/KiCad/share/kicad/library/7408
LibName13=C:/Program Files/KiCad/share/kicad/library/74138
LibName14=C:/Program Files/KiCad/share/kicad/library/74148
LibName15=C:/Program Files/KiCad/share/kicad/library/74151
LibName16=C:/Program Files/KiCad/share/kicad/library/74541
LibName17=C:/Program Files/KiCad/share/kicad/library/ac-dc
LibName18=C:/Program Files/KiCad/share/kicad/library/actel
LibName19=C:/Program Files/KiCad/share/kicad/library/adc-dac
LibName20=C:/Program Files/KiCad/share/kicad/library/Altera
LibName21=C:/Program Files/KiCad/share/kicad/library/analog_devices
LibName22=C:/Program Files/KiCad/share/kicad/library/analog_switches
LibName23=C:/Program Files/KiCad/share/kicad/library/ANT
LibName24=C:/Program Files/KiCad/share/kicad/library/AP6502
LibName25=C:/Program Files/KiCad/share/kicad/library/arduino
LibName26=C:/Program Files/KiCad/share/kicad/library/Arduino_As_Uno-cache
LibName27=C:/Program Files/KiCad/share/kicad/library/Arduino_Mega-cache
LibName28=C:/Program Files/KiCad/share/kicad/library/Arduino_Nano-cache
LibName29=C:/Program Files/KiCad/share/kicad/library/atmel
LibName30=C:/Program Files/KiCad/share/kicad/library/audio
LibName31=C:/Program Files/KiCad/share/kicad/library/AUDIO-JACK-3
LibName32=C:/Program Files/KiCad/share/kicad/library/BATTERY
LibName33=C:/Program Files/KiCad/share/kicad/library/BELFUSE-08B0-1X1T-06-F
LibName34=C:/Program Files/KiCad/share/kicad/library/brooktre
LibName35=C:/Program Files/KiCad/share/kicad/library/C
LibName36=C:/Program Files/KiCad/share/kicad/library/cmos_ieee
LibName37=C:/Program Files/KiCad/share/kicad/library/cmos4000
LibName38=C:/Program Files/KiCad/share/kicad/library/conn
LibName39=C:/Program Files/KiCad/share/kicad/library/contrib
LibName40=C:/Program Files/KiCad/share/kicad/library/CP
LibName41=C:/Program Files/KiCad/share/kicad/library/CRYSTAL
LibName42=C:/Program Files/KiCad/share/kicad/library/CRYSTAL-14
LibName43=C:/Program Files/KiCad/share/kicad/library/CVAR
LibName44=C:/Program Files/KiCad/share/kicad/library/cypress
LibName45=C:/Program Files/KiCad/share/kicad/library/dc-dc
LibName46=C:/Program Files/KiCad/share/kicad/library/device
LibName47=C:/Program Files/KiCad/share/kicad/library/digital-audio
LibName48=C:/Program Files/KiCad/share/kicad/library/diode
LibName49=C:/Program Files/KiCad/share/kicad/library/DIODES-AP3211
LibName50=C:/Program Files/KiCad/share/kicad/library/DIODESCH
LibName51=C:/Program Files/KiCad/share/kicad/library/DIODEZENER
LibName52=C:/Program Files/KiCad/share/kicad/library/display
LibName53=C:/Program Files/KiCad/share/kicad/library/dsp
LibName54=C:/Program Files/KiCad/share/kicad/library/EDISON-BULB-E10
LibName55=C:/Program Files/KiCad/share/kicad/library/EDISON-SOCKET-E10
LibName56=C:/Program Files/KiCad/share/kicad/library/elec-unifil
LibName57=C:/Program Files/KiCad/share/kicad/library/ENC28J60
LibName58=C:/Program Files/KiCad/share/kicad/library/ESD_Protection
LibName59=C:/Program Files/KiCad/share/kicad/library/ftdi
LibName60=C:/Program Files/KiCad/share/kicad/library/FTDI-PLUG
LibName61=C:/Program Files/KiCad/share/kicad/library/gennum
LibName62=C:/Program Files/KiCad/share/kicad/library/GNDPWR
LibName63=C:/Program Files/KiCad/share/kicad/library/graphic
LibName64=C:/Program Files/KiCad/share/kicad/library/hc11
LibName65=C:/Program Files/KiCad/share/kicad/library/INDUCTOR
LibName66=C:/Program Files/KiCad/share/kicad/library/intel
LibName67=C:/Program Files/KiCad/share/kicad/library/INTEL-EDISON-COMPUTE-MODULE
LibName68=C:/Program Files/KiCad/share/kicad/library/interface
LibName69=C:/Program Files/KiCad/share/kicad/library/ir
LibName70=C:/Program Files/KiCad/share/kicad/library/JTAG
LibName71=C:/Program Files/KiCad/share/kicad/library/JTAG10
LibName72=C:/Program Files/KiCad/share/kicad/library/Lattice
LibName73=C:/Program Files/KiCad/share/kicad/library/LATTICE-LC4256
LibName74=C:/Program Files/KiCad/share/kicad/library/LED
LibName75=C:/Program Files/KiCad/share/kicad/library/LED-BI
LibName76=C:/Program Files/KiCad/share/kicad/library/LED-BI-COMMON-CATHODE
LibName77=C:/Program Files/KiCad/share/kicad/library/linear
LibName78=C:/Program Files/KiCad/share/kicad/library/LM324
LibName79=C:/Program Files/KiCad/share/kicad/library/LM1875
LibName80=C:/Program Files/KiCad/share/kicad/library/logo
LibName81=C:/Program Files/KiCad/share/kicad/library/MAX3221
LibName82=C:/Program Files/KiCad/share/kicad/library/maxim
LibName83=C:/Program Files/KiCad/share/kicad/library/MC33926
LibName84=C:/Program Files/KiCad/share/kicad/library/MC34063A
LibName85=C:/Program Files/KiCad/share/kicad/library/MCP49X1
LibName86=C:/Program Files/KiCad/share/kicad/library/MCP3204
LibName87=C:/Program Files/KiCad/share/kicad/library/MECH
LibName88=C:/Program Files/KiCad/share/kicad/library/memory
LibName89=C:/Program Files/KiCad/share/kicad/library/MIC2039
LibName90=C:/Program Files/KiCad/share/kicad/library/MIC2288
LibName91=C:/Program Files/KiCad/share/kicad/library/microchip
LibName92=C:/Program Files/KiCad/share/kicad/library/microchip_dspic33dsc
LibName93=C:/Program Files/KiCad/share/kicad/library/microchip_pic10mcu
LibName94=C:/Program Files/KiCad/share/kicad/library/microchip_pic12mcu
LibName95=C:/Program Files/KiCad/share/kicad/library/microchip_pic16mcu
LibName96=C:/Program Files/KiCad/share/kicad/library/microchip_pic18mcu
LibName97=C:/Program Files/KiCad/share/kicad/library/microchip_pic32mcu
LibName98=C:/Program Files/KiCad/share/kicad/library/microcontrollers
LibName99=C:/Program Files/KiCad/share/kicad/library/MICROSD-AMPHENOL-114-00841-68
LibName100=C:/Program Files/KiCad/share/kicad/library/MOSFET-N
LibName101=C:/Program Files/KiCad/share/kicad/library/MOSFET-N-123
LibName102=C:/Program Files/KiCad/share/kicad/library/MOSFET-N-134
LibName103=C:/Program Files/KiCad/share/kicad/library/MOSFET-P
LibName104=C:/Program Files/KiCad/share/kicad/library/motor_drivers
LibName105=C:/Program Files/KiCad/share/kicad/library/motorola
LibName106=C:/Program Files/KiCad/share/kicad/library/msp430
LibName107=C:/Program Files/KiCad/share/kicad/library/nordicsemi
LibName108=C:/Program Files/KiCad/share/kicad/library/NPN
LibName109=C:/Program Files/KiCad/share/kicad/library/nRF8001
LibName110=C:/Program Files/KiCad/share/kicad/library/nxp_armmcu
LibName111=C:/Program Files/KiCad/share/kicad/library/onsemi
LibName112=C:/Program Files/KiCad/share/kicad/library/OPAMP-DUAL
LibName113=C:/Program Files/KiCad/share/kicad/library/opto
LibName114=C:/Program Files/KiCad/share/kicad/library/Oscillators
LibName115=C:/Program Files/KiCad/share/kicad/library/P01
LibName116=C:/Program Files/KiCad/share/kicad/library/P02
LibName117=C:/Program Files/KiCad/share/kicad/library/P03
LibName118=C:/Program Files/KiCad/share/kicad/library/P05
LibName119=C:/Program Files/KiCad/share/kicad/library/P06
LibName120=C:/Program Files/KiCad/share/kicad/library/P06-MOTOR
LibName121=C:/Program Files/KiCad/share/kicad/library/P08
LibName122=C:/Program Files/KiCad/share/kicad/library/P10
LibName123=C:/Program Files/KiCad/share/kicad/library/P22
LibName124=C:/Program Files/KiCad/share/kicad/library/P24
LibName125=C:/Program Files/KiCad/share/kicad/library/philips
LibName126=C:/Program Files/KiCad/share/kicad/library/PHOTO_TRANSISTOR
LibName127=C:/Program Files/KiCad/share/kicad/library/PIEZO
LibName128=C:/Program Files/KiCad/share/kicad/library/PNP
LibName129=C:/Program Files/KiCad/share/kicad/library/POT
LibName130=C:/Program Files/KiCad/share/kicad/library/power
LibName131=C:/Program Files/KiCad/share/kicad/library/Power_Management
LibName132=C:/Program Files/KiCad/share/kicad/library/powerint
LibName133=C:/Program Files/KiCad/share/kicad/library/pspice
LibName134=C:/Program Files/KiCad/share/kicad/library/PWR_FLAG
LibName135=C:/Program Files/KiCad/share/kicad/library/R
LibName136=C:/Program Files/KiCad/share/kicad/library/RASPBERRYPI
LibName137=C:/Program Files/KiCad/share/kicad/library/RBUS8
LibName138=C:/Program Files/KiCad/share/kicad/library/references
LibName139=C:/Program Files/KiCad/share/kicad/library/regul
LibName140=C:/Program Files/KiCad/share/kicad/library/relays
LibName141=C:/Program Files/KiCad/share/kicad/library/rfcom
LibName142=C:/Program Files/KiCad/share/kicad/library/ROBOT-P10-IO
LibName143=C:/Program Files/KiCad/share/kicad/library/RS-232-DB-9-DTE
LibName144=C:/Program Files/KiCad/share/kicad/library/sensors
LibName145=C:/Program Files/KiCad/share/kicad/library/silabs
LibName146=C:/Program Files/KiCad/share/kicad/library/siliconi
LibName147=C:/Program Files/KiCad/share/kicad/library/SKYWORKS-AAT1217-3.3
LibName148=C:/Program Files/KiCad/share/kicad/library/SPDT
LibName149=C:/Program Files/KiCad/share/kicad/library/SPST
LibName150=C:/Program Files/KiCad/share/kicad/library/SPST-4PIN
LibName151=C:/Program Files/KiCad/share/kicad/library/SST25VF032B-S2A
LibName152=C:/Program Files/KiCad/share/kicad/library/SST26VF032B
LibName153=C:/Program Files/KiCad/share/kicad/library/ST-LIS3MDL
LibName154=C:/Program Files/KiCad/share/kicad/library/stm8
LibName155=C:/Program Files/KiCad/share/kicad/library/stm32
LibName156=C:/Program Files/KiCad/share/kicad/library/STM32-32PIN
LibName157=C:/Program Files/KiCad/share/kicad/library/STM32-48PIN
LibName158=C:/Program Files/KiCad/share/kicad/library/STM32-64PIN
LibName159=C:/Program Files/KiCad/share/kicad/library/ST-SWD
LibName160=C:/Program Files/KiCad/share/kicad/library/supertex
LibName161=C:/Program Files/KiCad/share/kicad/library/SWD
LibName162=C:/Program Files/KiCad/share/kicad/library/switches
LibName163=C:/Program Files/KiCad/share/kicad/library/texas
LibName164=C:/Program Files/KiCad/share/kicad/library/TI-ADS7866
LibName165=C:/Program Files/KiCad/share/kicad/library/TICC3000
LibName166=C:/Program Files/KiCad/share/kicad/library/TIREF30XX
LibName167=C:/Program Files/KiCad/share/kicad/library/TP
LibName168=C:/Program Files/KiCad/share/kicad/library/transf
LibName169=C:/Program Files/KiCad/share/kicad/library/transistors
LibName170=C:/Program Files/KiCad/share/kicad/library/TSV631
LibName171=C:/Program Files/KiCad/share/kicad/library/ttl_ieee
LibName172=C:/Program Files/KiCad/share/kicad/library/TXB0108-PW
LibName173=C:/Program Files/KiCad/share/kicad/library/USB
LibName174=C:/Program Files/KiCad/share/kicad/library/USBAB
LibName175=C:/Program Files/KiCad/share/kicad/library/valves
LibName176=C:/Program Files/KiCad/share/kicad/library/Vcc
LibName177=C:/Program Files/KiCad/share/kicad/library/Vdd
LibName178=C:/Program Files/KiCad/share/kicad/library/video
LibName179=C:/Program Files/KiCad/share/kicad/library/VIN
LibName180=C:/Program Files/KiCad/share/kicad/library/VREG
LibName181=C:/Program Files/KiCad/share/kicad/library/VREG_VOUTCENTER
LibName182=C:/Program Files/KiCad/share/kicad/library/Xicor
LibName183=C:/Program Files/KiCad/share/kicad/library/xilinx
LibName184=C:/Program Files/KiCad/share/kicad/library/Zilog
LibName185=B:/KiCAD/share/kicad/library/aleksmk/altera
LibName186=B:/KiCAD/share/kicad/library/aleksmk/analog-devices
LibName187=B:/KiCAD/share/kicad/library/aleksmk/conn_mics
LibName188=B:/KiCAD/share/kicad/library/aleksmk/lt
LibName189=B:/KiCAD/share/kicad/library/aleksmk/max
LibName190=B:/KiCAD/share/kicad/library/aleksmk/opamps
LibName191=B:/KiCAD/share/kicad/library/aleksmk/random-mics
LibName192=B:/KiCAD/share/kicad/library/aleksmk/relays-a
LibName193=B:/KiCAD/share/kicad/library/aleksmk/switches
LibName194=B:/KiCAD/share/kicad/library/aleksmk/ti
LibName195=B:/KiCAD/share/kicad/library/aleksmk/transistors-mics
LibName196=B:/KiCAD/share/kicad/library/aleksmk/txs2sa-relay
LibName197=B:/Dropbox/michiele/Aruino/PCB Ontwerp/KiCAD/share/kicad/library/ander/ok-74logic
LibName198=B:/Dropbox/michiele/Aruino/PCB Ontwerp/KiCAD/share/kicad/library/ander/ok-con-generic
LibName199=B:/Dropbox/michiele/Aruino/PCB Ontwerp/KiCAD/share/kicad/library/ander/ok-diodes
LibName200=B:/Dropbox/michiele/Aruino/PCB Ontwerp/KiCAD/share/kicad/library/ander/ok-generic
LibName201=B:/Dropbox/michiele/Aruino/PCB Ontwerp/KiCAD/share/kicad/library/ander/ok-ic-analog
LibName202=B:/Dropbox/michiele/Aruino/PCB Ontwerp/KiCAD/share/kicad/library/ander/ok-ic-atmel
LibName203=B:/Dropbox/michiele/Aruino/PCB Ontwerp/KiCAD/share/kicad/library/ander/ok-ic-com
LibName204=B:/Dropbox/michiele/Aruino/PCB Ontwerp/KiCAD/share/kicad/library/ander/ok-ic-memory
LibName205=B:/Dropbox/michiele/Aruino/PCB Ontwerp/KiCAD/share/kicad/library/ander/ok-ic-power
LibName206=B:/Dropbox/michiele/Aruino/PCB Ontwerp/KiCAD/share/kicad/library/ander/ok-ic-special
LibName207=B:/Dropbox/michiele/Aruino/PCB Ontwerp/KiCAD/share/kicad/library/ander/ok-ic-stm32
LibName208=B:/Dropbox/michiele/Aruino/PCB Ontwerp/KiCAD/share/kicad/library/ander/ok-jacks
LibName209=B:/Dropbox/michiele/Aruino/PCB Ontwerp/KiCAD/share/kicad/library/ander/ok-opto
LibName210=B:/Dropbox/michiele/Aruino/PCB Ontwerp/KiCAD/share/kicad/library/ander/ok-relay
LibName211=B:/Dropbox/michiele/Aruino/PCB Ontwerp/KiCAD/share/kicad/library/ander/ok-switches
LibName212=B:/Dropbox/michiele/Aruino/PCB Ontwerp/KiCAD/share/kicad/library/ander/ok-transformers
LibName213=B:/Dropbox/michiele/Aruino/PCB Ontwerp/KiCAD/share/kicad/library/ander/ok-transistors
LibName214=B:/Dropbox/michiele/Aruino/PCB Ontwerp/KiCAD/share/kicad/library/ander/pot_us
LibName215=B:/Dropbox/michiele/Aruino/PCB Ontwerp/KiCAD/share/kicad/library/ander/ssm2301
LibName216=arduino_shield_michiel-1
LibName217=michiel TM1637
LibName218=Pappavis_logo_2klr
LibName219=Sovjet_simpits_logo01
LibName220=arduino
LibName221=atmega328
LibName222=freetronics_schematic
LibName223=power
LibName224=w_analog
LibName225=w_connectors
LibName226=w_device
LibName227=w_logic
LibName228=w_memory
LibName229=w_microcontrollers
LibName230=w_opto
LibName231=w_relay
LibName232=w_rtx
LibName233=w_transistor
LibName234=w_vacuum
